feat: update AInput & ASelect
add-eus/ui-kit pull request #114
Opened 2024-12-02 17:19 UTC by Hexya

2024-12-03 07:17 UTC, maximeallanic approved these changes

2024-12-03 16:45 UTC, maximeallanic approved these changes

2024-12-04 08:45 UTC, maximeallanic commented on components/AInput.vue
> +    <template v-if="type === 'text'">
```suggestion
    <template v-else>
```

2024-12-04 08:50 UTC, maximeallanic requested changes

2024-12-04 08:50 UTC, maximeallanic commented on components/AInput.vue
> +    <template v-if="type === 'password'">
```suggestion
    <template v-else-if="type === 'password'">
```

2024-12-06 13:09 UTC, asalsa commented
Hello, je fais mes retours ici pour l'UI kit (comme demandé par Maxime) : 

1. DatePicker : 
- Problème taille de typo > passer 12 à 14 (pour garder toujours la même logique sur tous les inputs)
- Par défaut en locale FR ou pas important en soit ?

2. Input :
- On ne peut pas avoir d'input sans label
- Transition entre l'état par défaut et l'état filled, y'en aura un (transition font size + position) ? ==> Exemple : https://codepen.io/avstorm/pen/gKGbxo
- Phone ==> Flag - Indicator - arrow => Augmenter la taille (passer de .8em à 1em) + laisser un peu de marge entre l'indicateur et l'arrow (prendre la même valeur de margin qu'avec le flag et l'indicateur)

3. TIme : 
- Si on renseigne une valeur à la mano et que l'on renseigne la valeur via la dropdown, le placement des valeurs dans l'input n'est pas la même (un aligné à droite et l'autre à gauche et l'un est plus haut que l'autre)

4. Select : 
- Même remarque que pour les 2 premiers points sur les inputs

2024-12-10 07:55 UTC, merged