Ds 58 login rework
add-eus/ui-kit pull request #15
Opened 2024-05-07 13:29 UTC by Hexya

2024-05-07 15:05 UTC, maximeallanic requested changes

2024-05-07 15:05 UTC, maximeallanic commented on components/ADButton.vue
> +  },
On aura pas de bouton arrondis ou carré, par contre on aura surement des boutons outlined

2024-05-07 15:11 UTC, Hexya commented on scss/_color-declaration.scss
> +
Faudrait qu'on soit raccord aujourd'hui le pink s'apelle primary sur les maquettes que tu viens de m'envoyer, ou on update les maquettes ou on passe le pink en primary

2024-05-14 13:44 UTC, maximeallanic approved these changes

2024-05-15 10:41 UTC, Hexya commented
Je ferais un rework globals en implémentant toutes colors que Lorène a définis

2024-05-15 11:09 UTC, maximeallanic approved these changes

2024-05-15 11:09 UTC, merged