feat: add dropdown and search component
add-eus/ui-kit pull request #24
Opened 2024-05-27 11:45 UTC by maximeallanic

2024-05-27 11:58 UTC, Hexya requested changes

2024-05-27 11:58 UTC, Hexya commented on components/ACard.vue
> +  <div class="a-card">
Si tu renomme les class ici faudra aussi faire une repasse sur tout les endroits ou ces class sont utilisé dans l'ui-kit et l'app
Exemple sur l'ui-kit AModal utilise ad-card, ad-card-head, ad-card-body..
Exemple sur app ModapProfileEdit utilise ad-modal-content et ad-card

2024-05-27 11:59 UTC, maximeallanic commented on components/ACard.vue
> +  <div class="a-card">
T'étais pas censé l'avoiir fait?

2024-05-27 11:59 UTC, maximeallanic commented on components/ACard.vue
> +  <div class="a-card">
Je le fais du coup

2024-05-27 12:04 UTC, maximeallanic commented on components/ACard.vue
> +  <div class="a-card">
Le renommage se fait dans cette pr:
https://github.com/add-eus/application/pull/729

2024-05-28 08:40 UTC, Hexya approved these changes

2024-05-28 08:42 UTC, merged