refactor: rework notification store
add-eus/ui-kit pull request #25
Opened 2024-05-27 13:14 UTC by charlesbl

2024-05-27 13:52 UTC, maximeallanic requested changes

2024-05-27 13:52 UTC, maximeallanic commented on stores/notification.ts
> -            if (!notyf) notyf = new Notyf();
T'as une erreur dans les builds, je ne sais toujours pas pourquoi ca fait cela. Mais c'est pour cette erreur que j'ai instancié Notyf à cette endroit là.

2024-05-27 14:34 UTC, charlesbl commented on stores/notification.ts
> -            if (!notyf) notyf = new Notyf();
Ouais j'étais en train de me battre avec histoire justement.
Pour je ne sais quelle raison, j'ai besoin d'utiliser un require() avec histoire.

2024-05-27 15:20 UTC, maximeallanic commented on stores/notification.ts
> -            if (!notyf) notyf = new Notyf();
C'était pas plus propre ce que j'avais fais? ><'

2024-05-28 07:27 UTC, maximeallanic commented on stores/notification.ts
```suggestion
// ou export
function getNotyf() {
  if (!module.notyf)
    module.notyf = new Notyf();
  return module.notyf;
}
```

2024-05-28 07:45 UTC, charlesbl commented on stores/notification.ts
module et exports fonctionne pas, obligé d'utiliser window

2024-05-28 08:07 UTC, maximeallanic approved these changes

2024-05-28 08:54 UTC, merged