feat: add ANumberAnim & story
add-eus/ui-kit pull request #28
Opened 2024-05-29 15:57 UTC by Hexya

2024-05-30 08:51 UTC, maximeallanic requested changes
Renommer en ANumberAnimated. Faut eviter les noms raccourcis

2024-05-30 08:51 UTC, maximeallanic commented on stories/components/ANumberAnim.story.vue
> +- `percent` (boolean, optional, default: false): Add a % to the number.
Si tu peux mettre plutôt un suffixe que % et tu lui passes un string.
Ça laissera plus de possibilité pour plus tard

2024-05-30 08:51 UTC, maximeallanic commented on stories/components/ANumberAnim.story.vue
> +# ALoader
Le nom n'est pas bon

2024-05-30 08:51 UTC, maximeallanic commented on components/ANumberAnim.vue
> +};
Peut être utiliser useTransition pour ŕeduire la quantité de ligne:
https://vueuse.org/core/useTransition/

2024-05-30 08:52 UTC, maximeallanic commented on components/ANumberAnim.vue
> +};
Et les performances

2024-05-31 07:46 UTC, maximeallanic requested changes
Il faudrait bloquer l'usage des progress bar à l'unité, plutôt que plusieurs unes sous les autres. Si on veut en mettre 2 à l'horizontal par exemple.
Il faut utiliser dans le parametre color la couleur plutot que la variable scss

2024-05-31 09:26 UTC, Hexya commented
> Il faudrait bloquer l'usage des progress bar à l'unité, plutôt que plusieurs unes sous les autres. Si on veut en mettre 2 à l'horizontal par exemple. Il faut utiliser dans le parametre color la couleur plutot que la variable scss

Ca ne ferait qu'enlever une feature non ? Rien n'empêche de ne mettre qu'une seule valeur pour placer les bars a l'horizontal mais si tu pense que c'est mieux je peux lock ça à une seule progress bar.
Pour la couleur tu préfèrerais que je récupère ça de cette manière ? `background: 'var(--a-' + color + ')'` Je peux mais ça laisse moins de liberté si on veux implémenter une couleur custom, sauf si tu veux absolument restreindre à l'utilisation de couleur existante.

2024-05-31 11:12 UTC, maximeallanic commented
> > Il faudrait bloquer l'usage des progress bar à l'unité, plutôt que plusieurs unes sous les autres. Si on veut en mettre 2 à l'horizontal par exemple. Il faut utiliser dans le parametre color la couleur plutot que la variable scss
> 
> Ca ne ferait qu'enlever une feature non ? Rien n'empêche de ne mettre qu'une seule valeur pour placer les bars a l'horizontal mais si tu pense que c'est mieux je peux lock ça à une seule progress bar. Pour la couleur tu préfèrerais que je récupère ça de cette manière ? `background: 'var(--a-' + color + ')'` Je peux mais ça laisse moins de liberté si on veux implémenter une couleur custom, sauf si tu veux absolument restreindre à l'utilisation de couleur existante.

Dans l'usage je vois aucun ui-kit qui permet d'afficher plusieurs progress bar sur le meme composant. IPar contre il y a des systèmes pour avoir plusieurs progressbar imbriqué:
![image](https://github.com/add-eus/ui-kit/assets/7780671/5a24becc-f7f7-49b9-9a5c-cd460c25f24c)
Le problème d'avoir trop feature sur chaque composant, c'est qu'on risque d'avoir une doc trop lourde à long terme.
Et pour les couleurs, tu fais pareil que dans les autres composant, en utilisant useColor.

2024-06-05 11:28 UTC, maximeallanic requested changes
> Renommer en ANumberAnimated. Faut eviter les noms raccourcis

Il manque ca

2024-06-05 12:45 UTC, maximeallanic requested changes
Il reste se fichier à renommer:
stories/components/ANumberAnim.story.vue

2024-06-07 06:45 UTC, maximeallanic approved these changes

2024-06-10 12:41 UTC, merged