feat: add crop component and store
add-eus/ui-kit pull request #29
Opened 2024-05-31 10:31 UTC by maximeallanic

2024-05-31 15:05 UTC, charlesbl approved these changes

2024-05-31 15:05 UTC, charlesbl requested changes
Oups, je voulais pas approve

2024-06-03 09:18 UTC, maximeallanic commented on components/Prompt/ACropPrompt.vue
> +export interface AConfirmPromptProps extends /* @vue-ignore */ ACropProps {
Typescript aime pas les extends sur les interfaces :'(

2024-06-03 09:21 UTC, charlesbl approved these changes

2024-06-03 12:09 UTC, merged